#GET:MO1
GET http://localhost:5039/TMResearch/M01/1
###
GET http://localhost:5039/TMResearch/M01
###
GET http://localhost:5039/TMResearch/
###
GET http://localhost:5039/
###
GET http://localhost:5039/V2/TMResearch/M01
###
GET http://localhost:5039/V3/TMResearch/DDD/M01
###

#GET:MO2
GET http://localhost:5039/V2
###
GET http://localhost:5039/V2/TMResearch
###
GET http://localhost:5039/V2/TMResearch/M02
###
GET http://localhost:5039/TMResearch/M02
###
GET http://localhost:5039/V3/TMResearch/DDD/M02
###

#GET:M03
GET http://localhost:5039/V3
###
GET http://localhost:5039/V3/TMResearch/DDD/
###
GET http://localhost:5039/V3/TMResearch/DDD/M03
###

#GET:MXX
GET http://localhost:5039/otherURI
